"""100+ unique questions used by the daily quiz & survey.
Each user gets a deterministic shuffle of 20 questions per day.
"""

QUIZ_QUESTIONS = [
    {"q": "What is the capital of India?", "options": ["Mumbai", "New Delhi", "Kolkata", "Chennai"], "answer": 1},
    {"q": "Which planet is known as the Red Planet?", "options": ["Earth", "Venus", "Mars", "Jupiter"], "answer": 2},
    {"q": "Currency of Japan?", "options": ["Yuan", "Won", "Yen", "Ringgit"], "answer": 2},
    {"q": "How many continents are there?", "options": ["5", "6", "7", "8"], "answer": 2},
    {"q": "Largest ocean on Earth?", "options": ["Atlantic", "Indian", "Arctic", "Pacific"], "answer": 3},
    {"q": "Who painted the Mona Lisa?", "options": ["Van Gogh", "Picasso", "Da Vinci", "Michelangelo"], "answer": 2},
    {"q": "Which gas do plants absorb from the air?", "options": ["Oxygen", "Hydrogen", "Carbon Dioxide", "Nitrogen"], "answer": 2},
    {"q": "Speed of light in vacuum (approx)?", "options": ["3×10^5 km/s", "3×10^6 km/s", "3×10^8 m/s", "3×10^10 m/s"], "answer": 2},
    {"q": "Square root of 144?", "options": ["10", "11", "12", "14"], "answer": 2},
    {"q": "Tallest mountain in the world?", "options": ["K2", "Kangchenjunga", "Everest", "Makalu"], "answer": 2},
    {"q": "Author of 'Hamlet'?", "options": ["Dickens", "Shakespeare", "Tolstoy", "Twain"], "answer": 1},
    {"q": "National animal of India?", "options": ["Lion", "Elephant", "Tiger", "Peacock"], "answer": 2},
    {"q": "Which is the longest river in the world?", "options": ["Amazon", "Nile", "Yangtze", "Mississippi"], "answer": 1},
    {"q": "Smallest prime number?", "options": ["0", "1", "2", "3"], "answer": 2},
    {"q": "Which is the largest desert in the world?", "options": ["Sahara", "Gobi", "Antarctic", "Arabian"], "answer": 2},
    {"q": "How many bones in adult human body?", "options": ["198", "206", "212", "220"], "answer": 1},
    {"q": "Chemical symbol for gold?", "options": ["Gd", "Go", "Au", "Ag"], "answer": 2},
    {"q": "Who invented the telephone?", "options": ["Edison", "Bell", "Tesla", "Marconi"], "answer": 1},
    {"q": "Year India got independence?", "options": ["1945", "1947", "1950", "1942"], "answer": 1},
    {"q": "First president of USA?", "options": ["Lincoln", "Jefferson", "Washington", "Adams"], "answer": 2},
    {"q": "Which language has the most native speakers?", "options": ["English", "Spanish", "Hindi", "Mandarin"], "answer": 3},
    {"q": "What is H2O?", "options": ["Salt", "Sugar", "Water", "Oxygen"], "answer": 2},
    {"q": "Largest mammal?", "options": ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"], "answer": 1},
    {"q": "Number of players in a cricket team?", "options": ["9", "10", "11", "12"], "answer": 2},
    {"q": "Which is the hottest planet?", "options": ["Mercury", "Venus", "Mars", "Sun"], "answer": 1},
    {"q": "Currency of UK?", "options": ["Euro", "Dollar", "Pound", "Franc"], "answer": 2},
    {"q": "How many sides does a hexagon have?", "options": ["5", "6", "7", "8"], "answer": 1},
    {"q": "Who wrote the Indian national anthem?", "options": ["Tagore", "Gandhi", "Nehru", "Bose"], "answer": 0},
    {"q": "Capital of Australia?", "options": ["Sydney", "Melbourne", "Canberra", "Perth"], "answer": 2},
    {"q": "Largest country by area?", "options": ["China", "USA", "Russia", "Canada"], "answer": 2},
    {"q": "Common cold is caused by?", "options": ["Bacteria", "Virus", "Fungi", "Parasite"], "answer": 1},
    {"q": "Pi value rounded to 2 decimals?", "options": ["3.12", "3.14", "3.16", "3.18"], "answer": 1},
    {"q": "Element with atomic number 1?", "options": ["Helium", "Oxygen", "Hydrogen", "Carbon"], "answer": 2},
    {"q": "Who is known as the father of computers?", "options": ["Edison", "Babbage", "Turing", "Tesla"], "answer": 1},
    {"q": "Light year is a unit of?", "options": ["Time", "Distance", "Speed", "Mass"], "answer": 1},
    {"q": "Which is a noble gas?", "options": ["Oxygen", "Nitrogen", "Hydrogen", "Helium"], "answer": 3},
    {"q": "Who discovered gravity?", "options": ["Einstein", "Newton", "Galileo", "Bohr"], "answer": 1},
    {"q": "Largest organ in human body?", "options": ["Liver", "Brain", "Skin", "Heart"], "answer": 2},
    {"q": "Capital of France?", "options": ["Rome", "Madrid", "Paris", "Berlin"], "answer": 2},
    {"q": "First woman PM of India?", "options": ["Sushma Swaraj", "Indira Gandhi", "Pratibha Patil", "Mamta Banerjee"], "answer": 1},
    {"q": "How many colours in a rainbow?", "options": ["5", "6", "7", "8"], "answer": 2},
    {"q": "Which festival is called festival of lights?", "options": ["Holi", "Diwali", "Eid", "Christmas"], "answer": 1},
    {"q": "What does CPU stand for?", "options": ["Central Power Unit", "Central Processing Unit", "Computer Personal Unit", "Control Processing Unit"], "answer": 1},
    {"q": "Which is the smallest country?", "options": ["Monaco", "Maldives", "Vatican City", "Nauru"], "answer": 2},
    {"q": "Tallest waterfall in the world?", "options": ["Niagara", "Victoria", "Angel", "Iguazu"], "answer": 2},
    {"q": "Which is the national fruit of India?", "options": ["Banana", "Apple", "Mango", "Orange"], "answer": 2},
    {"q": "Who built the Taj Mahal?", "options": ["Akbar", "Shah Jahan", "Aurangzeb", "Babur"], "answer": 1},
    {"q": "Year of first moon landing?", "options": ["1965", "1967", "1969", "1971"], "answer": 2},
    {"q": "Which sea is between India and Africa?", "options": ["Arabian", "Red", "Caspian", "Black"], "answer": 0},
    {"q": "First indian in space?", "options": ["Rakesh Sharma", "Kalpana Chawla", "Sunita Williams", "Vikram Sarabhai"], "answer": 0},
    {"q": "Currency of USA?", "options": ["Pound", "Euro", "Dollar", "Yen"], "answer": 2},
    {"q": "Who invented electricity?", "options": ["Franklin", "Edison", "Tesla", "Faraday"], "answer": 1},
    {"q": "What gas do humans breathe in?", "options": ["Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"], "answer": 1},
    {"q": "Which is the longest bone in human body?", "options": ["Tibia", "Femur", "Humerus", "Radius"], "answer": 1},
    {"q": "Who wrote 'War and Peace'?", "options": ["Dostoyevsky", "Tolstoy", "Chekhov", "Pushkin"], "answer": 1},
    {"q": "Number of zeros in one million?", "options": ["5", "6", "7", "8"], "answer": 1},
    {"q": "Largest planet in our solar system?", "options": ["Saturn", "Jupiter", "Neptune", "Earth"], "answer": 1},
    {"q": "Who discovered penicillin?", "options": ["Pasteur", "Fleming", "Lister", "Salk"], "answer": 1},
    {"q": "Capital of Russia?", "options": ["Moscow", "Kyiv", "Minsk", "St. Petersburg"], "answer": 0},
    {"q": "Which country gifted Statue of Liberty to USA?", "options": ["Germany", "France", "UK", "Italy"], "answer": 1},
    {"q": "Which is the smallest planet?", "options": ["Mars", "Mercury", "Venus", "Pluto"], "answer": 1},
    {"q": "Sound travels fastest in?", "options": ["Air", "Water", "Vacuum", "Solid"], "answer": 3},
    {"q": "What is the freezing point of water in Celsius?", "options": ["0", "32", "100", "-10"], "answer": 0},
    {"q": "Largest island in the world?", "options": ["Madagascar", "Greenland", "Borneo", "Iceland"], "answer": 1},
    {"q": "Father of the Nation of India?", "options": ["Nehru", "Patel", "Gandhi", "Bose"], "answer": 2},
    {"q": "Which animal is known as 'Ship of the Desert'?", "options": ["Horse", "Camel", "Donkey", "Elephant"], "answer": 1},
    {"q": "Number of teeth in adult human?", "options": ["28", "30", "32", "34"], "answer": 2},
    {"q": "DNA stands for?", "options": ["Deoxyribonucleic Acid", "Diribonucleic Acid", "Double Nucleic Acid", "Deoxy Nitric Acid"], "answer": 0},
    {"q": "First man to climb Everest?", "options": ["Tenzing Norgay", "Edmund Hillary", "Reinhold Messner", "George Mallory"], "answer": 1},
    {"q": "Who wrote 'Discovery of India'?", "options": ["Gandhi", "Tagore", "Nehru", "Tilak"], "answer": 2},
    {"q": "Which acid is found in lemons?", "options": ["Acetic", "Citric", "Sulfuric", "Lactic"], "answer": 1},
    {"q": "Indian national flower?", "options": ["Rose", "Lily", "Lotus", "Sunflower"], "answer": 2},
    {"q": "Which country invented paper?", "options": ["India", "China", "Egypt", "Greece"], "answer": 1},
    {"q": "Capital of Pakistan?", "options": ["Karachi", "Lahore", "Islamabad", "Peshawar"], "answer": 2},
    {"q": "How many minutes in a day?", "options": ["1440", "1240", "1640", "2400"], "answer": 0},
    {"q": "Bulb is invented by?", "options": ["Newton", "Edison", "Tesla", "Watt"], "answer": 1},
    {"q": "Largest gland in human body?", "options": ["Pancreas", "Liver", "Thyroid", "Salivary"], "answer": 1},
    {"q": "Which is hardest natural substance?", "options": ["Gold", "Iron", "Diamond", "Quartz"], "answer": 2},
    {"q": "First Olympic games held in?", "options": ["Rome", "Athens", "Paris", "London"], "answer": 1},
    {"q": "Indian national bird?", "options": ["Parrot", "Peacock", "Eagle", "Sparrow"], "answer": 1},
    {"q": "Which is the deepest ocean trench?", "options": ["Mariana", "Tonga", "Java", "Puerto Rico"], "answer": 0},
    {"q": "Which vitamin is produced by sunlight?", "options": ["A", "B", "C", "D"], "answer": 3},
    {"q": "Capital of Canada?", "options": ["Toronto", "Ottawa", "Vancouver", "Montreal"], "answer": 1},
    {"q": "Year of World War 2 ending?", "options": ["1943", "1944", "1945", "1946"], "answer": 2},
    {"q": "Who invented the airplane?", "options": ["Wright Brothers", "Edison", "Da Vinci", "Tesla"], "answer": 0},
    {"q": "How many wonders of the world (modern)?", "options": ["5", "6", "7", "8"], "answer": 2},
    {"q": "Largest planet's name origin?", "options": ["Roman king of gods", "Greek god of war", "Egyptian sun god", "Norse god of thunder"], "answer": 0},
    {"q": "Which planet has rings?", "options": ["Mars", "Venus", "Saturn", "Mercury"], "answer": 2},
    {"q": "Father of Indian Constitution?", "options": ["Nehru", "Patel", "Ambedkar", "Rajaji"], "answer": 2},
    {"q": "What's the unit of electric current?", "options": ["Volt", "Ohm", "Ampere", "Watt"], "answer": 2},
    {"q": "Which is the longest wall in the world?", "options": ["Berlin Wall", "Great Wall of China", "Hadrian's Wall", "Walls of Babylon"], "answer": 1},
    {"q": "Who is known as the missile man of India?", "options": ["Kalam", "Sarabhai", "Bhabha", "Raman"], "answer": 0},
    {"q": "Capital of Germany?", "options": ["Munich", "Hamburg", "Berlin", "Frankfurt"], "answer": 2},
    {"q": "How many players in football team on field?", "options": ["9", "10", "11", "12"], "answer": 2},
    {"q": "Largest country in Africa?", "options": ["Egypt", "Nigeria", "Algeria", "South Africa"], "answer": 2},
    {"q": "Who is known as Bard of Avon?", "options": ["Shakespeare", "Wordsworth", "Keats", "Shelley"], "answer": 0},
    {"q": "Brain of computer is?", "options": ["RAM", "ROM", "CPU", "HDD"], "answer": 2},
    {"q": "Largest religion in India?", "options": ["Sikh", "Islam", "Hindu", "Christian"], "answer": 2},
    {"q": "Which river flows through Egypt?", "options": ["Amazon", "Nile", "Tigris", "Euphrates"], "answer": 1},
    {"q": "Who wrote 'Origin of Species'?", "options": ["Darwin", "Mendel", "Watson", "Hooke"], "answer": 0},
    {"q": "Currency of China?", "options": ["Yen", "Yuan", "Won", "Rupee"], "answer": 1},
    {"q": "Which is the largest sea?", "options": ["South China", "Caribbean", "Mediterranean", "Bering"], "answer": 0},
    {"q": "Boiling point of water in Celsius?", "options": ["90", "95", "100", "110"], "answer": 2},
    {"q": "Which planet is closest to Sun?", "options": ["Earth", "Venus", "Mercury", "Mars"], "answer": 2},
    {"q": "Who painted the Sistine Chapel?", "options": ["Da Vinci", "Michelangelo", "Raphael", "Donatello"], "answer": 1},
    {"q": "Which Indian state is the largest by area?", "options": ["UP", "MP", "Maharashtra", "Rajasthan"], "answer": 3},
    {"q": "Highest grossing film of all time (2024)?", "options": ["Avatar", "Avengers", "Titanic", "Star Wars"], "answer": 0},
]

SURVEY_QUESTIONS = [
    {"q": "How often do you use CashClick?", "options": ["Daily", "Weekly", "Rarely", "First time"]},
    {"q": "Favorite earning method?", "options": ["Tasks", "Spin", "Scratch", "Watch videos"]},
    {"q": "What's your preferred withdrawal amount?", "options": ["₹1", "₹100", "₹300", "₹500+"]},
    {"q": "Are app notifications useful?", "options": ["Very useful", "Sometimes", "Rarely", "Never"]},
    {"q": "How did you hear about us?", "options": ["Friend", "Telegram", "YouTube", "Other"]},
    {"q": "Preferred payment method?", "options": ["UPI", "Bank transfer", "Wallet", "Other"]},
    {"q": "How would you rate the app's UI?", "options": ["Excellent", "Good", "Average", "Poor"]},
    {"q": "Which feature do you want next?", "options": ["More tasks", "Higher rewards", "Referral bonus", "Mini-games"]},
    {"q": "Have you withdrawn money before?", "options": ["Yes, often", "Yes, once", "Not yet", "Will soon"]},
    {"q": "Daily time spent in app?", "options": ["<5 min", "5-15 min", "15-30 min", "30+ min"]},
    {"q": "Why do you prefer CashClick?", "options": ["Easy tasks", "Quick payouts", "Variety", "Bonuses"]},
    {"q": "Trust level for online earning apps?", "options": ["Very high", "High", "Moderate", "Low"]},
    {"q": "How likely to recommend to friend?", "options": ["Definitely", "Probably", "Maybe", "No"]},
    {"q": "Best time to complete tasks?", "options": ["Morning", "Afternoon", "Evening", "Night"]},
    {"q": "What's most important to you?", "options": ["High rewards", "Quick withdraw", "Easy tasks", "Variety"]},
    {"q": "Which social platform do you use most?", "options": ["WhatsApp", "Telegram", "Instagram", "YouTube"]},
    {"q": "Have you referred someone?", "options": ["Yes, many", "Yes, few", "Planning to", "Not yet"]},
    {"q": "Preferred quiz topic?", "options": ["GK", "Sports", "Movies", "Science"]},
    {"q": "How important are daily bonuses?", "options": ["Very", "Quite", "Somewhat", "Not really"]},
    {"q": "How long have you been using earn apps?", "options": ["<1 month", "1-6 months", "6-12 months", "1+ year"]},
    {"q": "Do you complete most tasks?", "options": ["Always", "Most", "Sometimes", "Few"]},
    {"q": "Issue with app loading?", "options": ["Never", "Sometimes", "Often", "Always"]},
    {"q": "Best feature you like?", "options": ["Tasks", "Withdraw", "Quizzes", "Daily Spin"]},
    {"q": "Daily checkin streak importance?", "options": ["Important", "Quite", "Less", "Not at all"]},
    {"q": "Which gift would excite you?", "options": ["Cash", "Amazon GC", "Mobile recharge", "Bonus pts"]},
    {"q": "How much you earn per day?", "options": ["<₹10", "₹10-50", "₹50-100", "₹100+"]},
    {"q": "Best withdrawal method?", "options": ["UPI", "Paytm", "Bank", "Amazon"]},
    {"q": "Preferred ad type?", "options": ["Short video", "Banner", "Survey", "Native"]},
    {"q": "App speed rating?", "options": ["Fast", "Decent", "Slow", "Crashes"]},
    {"q": "Where do you live?", "options": ["Metro", "Tier-1 city", "Tier-2/3", "Village"]},
    {"q": "Your age group?", "options": ["13-18", "19-25", "26-40", "40+"]},
    {"q": "Are you a student?", "options": ["Yes", "No", "Part-time", "Just graduated"]},
    {"q": "Phone you use?", "options": ["Android Premium", "Android Mid", "Android Budget", "iPhone"]},
    {"q": "Data connection?", "options": ["WiFi mostly", "4G", "5G", "Limited"]},
    {"q": "Why join CashClick?", "options": ["Extra income", "Time-pass", "Friend's referral", "Curiosity"]},
    {"q": "Are tasks easy to understand?", "options": ["Very easy", "Easy", "Hard", "Confusing"]},
    {"q": "App's reward fairness?", "options": ["Fair", "OK", "Could be better", "Unfair"]},
    {"q": "Which language do you prefer?", "options": ["English", "Hindi", "Regional", "Mixed"]},
    {"q": "Bug reports submitted?", "options": ["Never", "Once", "Few times", "Many"]},
    {"q": "Want push notifications?", "options": ["Yes daily", "Few/week", "Rarely", "Disable"]},
    {"q": "Preferred contact channel?", "options": ["Telegram", "Email", "In-app chat", "Phone"]},
    {"q": "App theme preference?", "options": ["Dark", "Light", "Auto", "No preference"]},
    {"q": "Which earning app is competitor?", "options": ["mRewards", "Loco", "Big Cash", "None"]},
    {"q": "Trust in payouts?", "options": ["Full", "Partial", "Doubtful", "First-time"]},
    {"q": "Want a leaderboard feature?", "options": ["Yes", "Maybe", "No", "Don't care"]},
    {"q": "Profile customization important?", "options": ["Very", "Yes", "Maybe", "No"]},
    {"q": "Family or friends use this app?", "options": ["Yes many", "Few", "One", "None"]},
    {"q": "Best onboarding experience?", "options": ["Quick", "Detailed", "Video tutorial", "Skip"]},
    {"q": "What would make you uninstall?", "options": ["No payouts", "Bugs", "Boring", "Too many ads"]},
    {"q": "Daily login importance?", "options": ["Very", "Quite", "Sometimes", "Never"]},
]
